### ISSUE TITLE
[BUG REPORT] [Linux, macOS] Administration privileges required for any commands

### ISSUE THREAD

**Issue by miosanlol** [edamametechnologies/edamame_posture_cli#1]
# Bug report

## Expected vs actual behavior

We should ask administration privileges only for commands requiring core calls

## Screenshots (if relevant)

<img width="1500" alt="Screenshot 2024-08-28 at 12 20 39" src="https://github.com/user-attachments/assets/004b0dd6-4d7b-4eb8-b161-a150b4018bd2">

**Comment by franklyonnet** [comment]
Fixed
